services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: certificado_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rede_distribuida

  redis:
    image: redis:alpine
    container_name: certificado_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rede_distribuida

volumes:
  rabbitmq_data:
  redis_data:

networks:
  rede_distribuida:
    driver: bridge